Add verbose option and ability to have owner with number in the name.

diff --git a/bin/git-same-repo-pr b/bin/git-same-repo-pr
--- a/bin/git-same-repo-pr
+++ b/bin/git-same-repo-pr
@@ -1,10 +1,25 @@
 #! /bin/bash
 
-OWNER=$(ruby -e "puts \`git remote -v\`.match(/git@github.com:([a-z\-]+)\/[a-z\-_.]+/)[1]")
+set -e
+
+VERBOSE=0
+
+while test $# -gt 0
+do
+  case "$1" in
+     -v) VERBOSE=1
+      ;;
+    --*) echo "invalid option $1"
+      exit 1
+      ;;
+      *) echo "invalid arg $1"
+      ;;
+  esac
+  shift
+done
+
+OWNER=$(ruby -e "puts \`git remote -v\`.match(/git@github.com:([0-9a-z\-]+)\/[0-9a-z\-_.]+/)[1]")
 BRANCH=$(ruby -e "puts \`git branch\`.match(/\n\*\ ([a-z0-9\-_]+)/)[1]")
 
-if [ -z $(which open) ]; then
-  hub pull-request -h ${OWNER}:${BRANCH}
-else
-  hub pull-request -h ${OWNER}:${BRANCH} | open
-fi
+[[ VERBOSE -eq 1 ]] && echo "hub pull-request -h ${OWNER}:${BRANCH}"
+hub pull-request -h ${OWNER}:${BRANCH}
